// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID                  int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Username            string         `gorm:"column:username;comment:用户登录名" json:"username"`                                         // 用户登录名
	Password            string         `gorm:"column:password;comment:用户登录密码" json:"password"`                                        // 用户登录密码
	Phone               string         `gorm:"column:phone;comment:用户手机号" json:"phone"`                                               // 用户手机号
	Age                 int32          `gorm:"column:age;comment:年龄" json:"age"`                                                      // 年龄
	Bmi                 int32          `gorm:"column:bmi;comment:BMI" json:"bmi"`                                                     // BMI
	MobilityValue       string         `gorm:"column:mobility_value;comment:MobilityValue" json:"mobility_value"`                     // MobilityValue
	AvailableTimeValues string         `gorm:"column:available_Time_values;comment:AvailableTimeValues" json:"available_Time_values"` // AvailableTimeValues
	Latitude            float64        `gorm:"column:latitude;comment:latitude" json:"latitude"`                                      // latitude
	Longitude           float64        `gorm:"column:longitude;comment:Longitude" json:"longitude"`                                   // Longitude
	CreatedAt           time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt           time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt           gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
